stages:
  - build

.build:
  tags:
    - linux
    - docker
    - liris
  stage: build
  image: coqorg/${CI_JOB_NAME}
  before_script:
    - if [ -n "${COMPILER_EDGE}" ]; then opam switch ${COMPILER_EDGE} && eval $(opam env); fi
    - opam update -y
    - opam config list
    - opam repo list
    - opam list
  script:
    - sudo chown -R coq:coq "$CI_PROJECT_DIR"
    - coq_makefile -f _CoqProject -o Makefile
    - make -j "$NJOBS"
#    - make install

coq:8.12:
  extends: .build

coq:8.13:
  extends: .build
